with-expecter: True
quiet: False
mockname: "{{.InterfaceName}}"
packages:
  github.com/a-novel/votes-service/pkg/dao:
    config:
      all: True
      outpkg: daomocks
      dir: pkg/dao/mocks
  github.com/a-novel/votes-service/pkg/services:
    config:
      all: True
      outpkg: servicesmocks
      dir: pkg/services/mocks
