// Code generated by mockery v2.33.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/a-novel/votes-service/pkg/models"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// CastVoteService is an autogenerated mock type for the CastVoteService type
type CastVoteService struct {
	mock.Mock
}

type CastVoteService_Expecter struct {
	mock *mock.Mock
}

func (_m *CastVoteService) EXPECT() *CastVoteService_Expecter {
	return &CastVoteService_Expecter{mock: &_m.Mock}
}

// Cast provides a mock function with given fields: ctx, tokenRaw, form, id, now
func (_m *CastVoteService) Cast(ctx context.Context, tokenRaw string, form models.VoteForm, id uuid.UUID, now time.Time) (*models.VotesSummary, error) {
	ret := _m.Called(ctx, tokenRaw, form, id, now)

	var r0 *models.VotesSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.VoteForm, uuid.UUID, time.Time) (*models.VotesSummary, error)); ok {
		return rf(ctx, tokenRaw, form, id, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, models.VoteForm, uuid.UUID, time.Time) *models.VotesSummary); ok {
		r0 = rf(ctx, tokenRaw, form, id, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VotesSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, models.VoteForm, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, tokenRaw, form, id, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CastVoteService_Cast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cast'
type CastVoteService_Cast_Call struct {
	*mock.Call
}

// Cast is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenRaw string
//   - form models.VoteForm
//   - id uuid.UUID
//   - now time.Time
func (_e *CastVoteService_Expecter) Cast(ctx interface{}, tokenRaw interface{}, form interface{}, id interface{}, now interface{}) *CastVoteService_Cast_Call {
	return &CastVoteService_Cast_Call{Call: _e.mock.On("Cast", ctx, tokenRaw, form, id, now)}
}

func (_c *CastVoteService_Cast_Call) Run(run func(ctx context.Context, tokenRaw string, form models.VoteForm, id uuid.UUID, now time.Time)) *CastVoteService_Cast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.VoteForm), args[3].(uuid.UUID), args[4].(time.Time))
	})
	return _c
}

func (_c *CastVoteService_Cast_Call) Return(_a0 *models.VotesSummary, _a1 error) *CastVoteService_Cast_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CastVoteService_Cast_Call) RunAndReturn(run func(context.Context, string, models.VoteForm, uuid.UUID, time.Time) (*models.VotesSummary, error)) *CastVoteService_Cast_Call {
	_c.Call.Return(run)
	return _c
}

// NewCastVoteService creates a new instance of CastVoteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCastVoteService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CastVoteService {
	mock := &CastVoteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
