// Code generated by mockery v2.33.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/a-novel/votes-service/pkg/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// GetUserVoteService is an autogenerated mock type for the GetUserVoteService type
type GetUserVoteService struct {
	mock.Mock
}

type GetUserVoteService_Expecter struct {
	mock *mock.Mock
}

func (_m *GetUserVoteService) EXPECT() *GetUserVoteService_Expecter {
	return &GetUserVoteService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, tokenRaw, targetID, target
func (_m *GetUserVoteService) Get(ctx context.Context, tokenRaw string, targetID uuid.UUID, target string) (*models.Vote, error) {
	ret := _m.Called(ctx, tokenRaw, targetID, target)

	var r0 *models.Vote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, string) (*models.Vote, error)); ok {
		return rf(ctx, tokenRaw, targetID, target)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, string) *models.Vote); ok {
		r0 = rf(ctx, tokenRaw, targetID, target)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Vote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tokenRaw, targetID, target)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserVoteService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type GetUserVoteService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenRaw string
//   - targetID uuid.UUID
//   - target string
func (_e *GetUserVoteService_Expecter) Get(ctx interface{}, tokenRaw interface{}, targetID interface{}, target interface{}) *GetUserVoteService_Get_Call {
	return &GetUserVoteService_Get_Call{Call: _e.mock.On("Get", ctx, tokenRaw, targetID, target)}
}

func (_c *GetUserVoteService_Get_Call) Run(run func(ctx context.Context, tokenRaw string, targetID uuid.UUID, target string)) *GetUserVoteService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *GetUserVoteService_Get_Call) Return(_a0 *models.Vote, _a1 error) *GetUserVoteService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetUserVoteService_Get_Call) RunAndReturn(run func(context.Context, string, uuid.UUID, string) (*models.Vote, error)) *GetUserVoteService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetUserVoteService creates a new instance of GetUserVoteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetUserVoteService(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetUserVoteService {
	mock := &GetUserVoteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
